# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

from dataclasses import dataclass, field
from typing import Union
from coretp.rv_enums import PagingMode, PageSize, PrivilegeMode, InterruptMode


@dataclass(frozen=True)
class TestEnv:
    """
    Test environment that can be used downstream to configure a series of tests.
    Generated by TestEnvSolver from a sequence of TestEnvCfg objects
    """

    reg_width: int = 64
    priv: PrivilegeMode = PrivilegeMode.M
    paging_mode: PagingMode = PagingMode.DISABLED
    g_paging_mode: PagingMode = PagingMode.DISABLED
    page_size: frozenset[PageSize] = field(default_factory=lambda: frozenset({PageSize.SIZE_4K}))
    hart_count: int = 1
    virtualized: bool = False  #: Whether the test environment is virtualized or in bare metal (hypervisor) mode
    deleg_excp_to: PrivilegeMode = PrivilegeMode.M
    deleg_intr_to: PrivilegeMode = PrivilegeMode.M  #: Target privilege mode for interrupt delegation via mideleg
    interrupt_mode: InterruptMode = InterruptMode.VECTORED  #: Interrupt vector mode (direct vs vectored)
    max_test_runs: int = 1000000  # Arbitrary large number to ensure test runs indefinitely

    def get_max_va_bits(self) -> int:
        """
        Helper to get the maximum number of bits for a virtual address

        :return: Maximum number of bits for VA
        :rtype: int
        """
        if self.paging_mode == PagingMode.SV39:
            return 39
        if self.paging_mode == PagingMode.SV48:
            return 48
        if self.paging_mode == PagingMode.SV57:
            return 57
        return self.reg_width
